### ISSUE TITLE
Applying plugin with the plugins DSL

### ISSUE THREAD

**Issue by luisalves00** [GoogleContainerTools/jib-extensions#132]
Is the extension released in a way that it can be used using Plugin DSL (https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) 

Example:
```groovy
	plugins {
		id("com.google.cloud.tools.jib-ownership-extension-gradle")
                ...
	}
```

tried and the artifact cannot be found while jib is:
```groovy
	plugins {
                ...
		id("com.google.cloud.tools.jib")
	}
```

thanks

**Comment by chanseokoh** [comment]
No, the extensions are not Gradle plugins and not meant to be "applied." You just want the classes in the JAR file available (i.e., be on the classpath) inside the build script.

**Comment by luisalves00** [comment]
It's a good point. Plan was to put

```
id("com.google.cloud.tools.jib-ownership-extension-gradle") version("${jibOwnershipVersion}") apply false
```

So it wasn't applied but loaded into the classpath.

I'll keep my OCD aside and add the buildscript part as you propose in documentation:
```groovy
buildscript {
  dependencies {
    classpath('com.google.cloud.tools:jib-ownership-extension-gradle:0.1.0')
  }
}
```
