### ISSUE TITLE
Cause: extension configured but not discovered on Jib runtime classpath: com.google.cloud.tools.jib.gradle.extension.springboot.JibSpringBootExtension

### ISSUE THREAD

**Issue by thaarbach** [GoogleContainerTools/jib-extensions#164]
Added JibSpringBootExtension to a Spring Boot  3.1.2  Application as descripted in the docs

Execution fails with 

`> error running extension 'com.google.cloud.tools.jib.plugins.extension.NullExtension': extension configured but not discovered on Jib runtime classpath: com.google.cloud.tools.jib.gradle.extension.springboot.JibSpringBootExtension`

At the top of the gradle script i added 

```
buildscript {
    dependencies {
        classpath('com.google.cloud.tools:jib-spring-boot-extension-gradle:0.1.0')
    }
}
```

Jib is configured as
```
jib {
    description """Creates an optimized docker images and push it do nexus
                   Usage: ./gradelew jib -Prepo=<docker-repository> -Pport=<exposedPort>
                  """
    from {
        image = "eclipse-temurin:17-jre"
    }
    to {
        image = "$repository/$project.name:$version"
        tags = ["latest"]
    }
    container {
        workingDirectory = "/"
        ports = [exposedPort]
        container.creationTime = "USE_CURRENT_TIMESTAMP"
        jvmFlags = [
            "-XX:+UseContainerSupport",
            "-XX:InitialRAMPercentage=50",
            "-XX:MaxRAMPercentage=100",
            "-XX:+ExitOnOutOfMemoryError",
            "-Djava.awt.headless=true",
            "-XX:+AlwaysPreTouch",
            "-Djava.security.egd=file:/dev/./urandom"
        ]
        environment = [
            SPRING_OUTPUT_ANSI_ENABLED: "ALWAYS",
            TZ                        : "Europe/Berlin"
        ]
    }
    pluginExtensions { 
        pluginExtension {
            implementation = 'com.google.cloud.tools.jib.gradle.extension.springboot.JibSpringBootExtension'
        }
    }
}
```

What is missing?

**Comment by suztomo** [comment]
> as descripted in the docs

Would you add the URL of the document?

**Comment by thaarbach** [comment]
@suztomo 
sorry, for my late answer.  Found it in the readme of spring-boot-extension

https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-spring-boot-extension-gradle

**Comment by mpeddada1** [comment]
Can you verify if it's available in the build script by using this [setup](https://github.com/GoogleContainerTools/jib-extensions/issues/133#issuecomment-1218307422)? Additionally, are you experiencing this when using particular `gradlew` version?

**Comment by alicejli** [comment]
Closing due to lack of response; please reopen with additional info if this is still an issue. Thanks!
