### ISSUE TITLE
Error in configuration example of jib-layer-filter-extension-maven

### ISSUE THREAD

**Issue by thomasfox** [GoogleContainerTools/jib-extensions#165]
In the configuration example in the Readme jib-extensions/first-party/jib-layer-filter-extension-maven/README.md, there is following snippet:
```
          </filters>
        </configuration>
        <!-- To create separate layers for parent dependencies-->
        <createParentDependencyLayers>true</createParentDependencyLayers>
      </pluginExtension>
```
This does not work, because, as noted in the javadoc of the Configuration class, the createParentDependencyLayers setting should be inside the configuration block and not outside. So the following would be correct:
```
          </filters>
          <!-- To create separate layers for parent dependencies-->
          <createParentDependencyLayers>true</createParentDependencyLayers>
        </configuration>
      </pluginExtension>

```

**Comment by zhumin8** [comment]
Thank you for noticing this. I've raised a pr to fix this.
