### ISSUE TITLE
The native-image extension does not detect .exe suffix on windows

### ISSUE THREAD

**Issue by bonitao** [GoogleContainerTools/jib-extensions#168]
Here are the commands I ran and the output I got.

```
./gradlew --no-configuration-cache tracker:nativeCompile
...
./gradlew --no-configuration-cache tracker:jibDockerBuild
...
> Task :tracker:jibDockerBuild FAILED
Running extension: com.google.cloud.tools.jib.gradle.extension.nativeimage.JibNativeImageExtension
Running Jib Native Image extension

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tracker:jibDockerBuild'.
> error running extension 'com.google.cloud.tools.jib.gradle.extension.nativeimage.JibNativeImageExtension': Native-image executable does not exist or not a file: C:\Users\davir\code\trash\svcs\tracker\build\native\nativeCompile\svcs.tracker
  Did you run the 'native-image:native-image' goal?
```

The `svcs.tracker` file indeed does not exit, but its windows counterpart, `svcs.tracker.exe` exists and should be used instead.

**Comment by mpeddada1** [comment]
If the plugin fails to detect the native image for some reason, you could manually specify the native image executable under the `imageName` property (shown in https://github.com/GoogleContainerTools/jib-extensions/blob/a34c7c730ec969b5bb8935e4eb707959868ff969/first-party/jib-native-image-extension-gradle/README.md#examples)
