### ISSUE TITLE
Documentation/example for gradle kotlin build

### ISSUE THREAD

**Issue by zurvan2** [GoogleContainerTools/jib-extensions#35]
I'm having no luck trying to use a jib extension in a gradle kotlin build. An example build.gradle.kts would be very useful.

**Comment by loosebazooka** [comment]
@zurvan2 thank you for bringing this up. We haven't done much kotlin work except for supporting the bare minimum. I think we can do a better job here. This is definitely a bug. We will add some documentation around this and think about how to support kotlin build files better.

**Comment by chanseokoh** [comment]
@zurvan2 we tried some ideas, and we were able to apply an extension to our [`ktor` sample](https://github.com/GoogleContainerTools/jib/tree/master/examples/ktor) with the following changes. I think this is less verbose.
```diff
diff --git a/examples/ktor/build.gradle.kts b/examples/ktor/build.gradle.kts
index b45c66d6..a5bd24b5 100644
--- a/examples/ktor/build.gradle.kts
+++ b/examples/ktor/build.gradle.kts
@@ -1,3 +1,9 @@
+buildscript {
+  dependencies {
+    classpath("com.google.cloud.tools:jib-layer-filter-extension-gradle:0.1.0")
+  }
+}
+
 plugins {
     application
     kotlin("jvm") version "1.3.10"
@@ -55,6 +61,18 @@ jib {
                 "-XX:+UseStringDeduplication"
         )
     }
+    pluginExtensions {
+        pluginExtension {
+            implementation = "com.google.cloud.tools.jib.gradle.extension.layerfilter.JibLayerFilterExtension"
+            configuration(Action<com.google.cloud.tools.jib.gradle.extension.layerfilter.Configuration> {
+              filters {
+                filter {
+                  glob = "**/*.jar"
+                }
+              }
+            })
+        }
+    }
 }
 
 repositories {
```

**Comment by loosebazooka** [comment]
To add to @chanseokoh, in our experiements, we discovered simply forcing the action type to `<...layerfilter.Configuration>` was enough to allow the type checker to accept this config.
