### ISSUE TITLE
Customize the order of jib filter，Jib filter extensions created layer order is not good

### ISSUE THREAD

**Issue by SamPeng87** [GoogleContainerTools/jib-extensions#56]
normal,jib create layers for:

```
libs
classes
resources
```
this is good layers for thin docker.but,Libs is too big, and there are some jar packages in it that may change frequently, so it is necessary to separate the layers to reflect the role of thin packages;

filter jib extensions is good job,but order is wrong,like this:

```
libs
classes
resources
new-layer-1
new-layer-2
```

if we only change some classes and resources.that change very small.but,new layers all need download again.that not good idea.
maybe,we can insert new layer  like this
```
libs
new-layer-1
new-layer-2
classes
resources
```

use jib extensions like this:

```
pluginExtensions {
            pluginExtension {
                implementation = 'com.google.cloud.tools.jib.gradle.extension.layerfilter.JibLayerFilterExtension'
                configuration {
                    filters {
                        filter {
                            glob = '/app/libs/google-*.jar'
                            toLayer = 'google dependencies'
                            after/before = "xxxx"
                        }
                    }
                }
            }
        }
```

**Comment by chanseokoh** [comment]
Hi @SamPeng87,

Thanks for the feedback.

> filter jib extensions is good job,but order is wrong,like this:
> 
> ```
> libs
> classes
> resources
> new-layer-1
> new-layer-2
> ```
> 
> if we only change some classes and resources.that change very small.but,new layers all need download again.that not good idea.

I'd like point out that this is not true. The order of layers doesn't matter. The order matters only when using `Dockerfile` and the Docker CLI to create and cache layers. With Jib, changing classes and resources will only rebuild the "classes" and "resources" layers. Also you'll only pull and push the "classes" and "resources" layers from/to registries.

**Comment by SamPeng87** [comment]
Hi @chanseokoh 

thanks for your reply,I research docker pull workflow again,you are right.

**Comment by stefanocke** [comment]
@chanseokoh , @SamPeng87  I have a similar situation and in my case "docker pull" seems always to download the layers "after" the changed one again.  So, in the example above, I changed resources, and docker pull did download new-layer-1 and new-layer-2.
When looking into the image with help of https://github.com/wagoodman/dive,  I see that the digests for new-layer-1 and new-layer-2 are still the same, but their IDs have changed.
For resources layer, digest and ID hs changed (of course).
I have no idea what is going wrong, but it seems, docker pull looks at the changed IDs and not on the stable digests in my case.
Docker Version: 20.10.21  (and Docker Desktop on Windows)

**Comment by vibbix** [comment]
I am having an issue with this too. A good chunk of OCI/Docker compatible container stores rely on previous hash just as much.
