### ISSUE TITLE
native image gradle extenstion too

### ISSUE THREAD

**Issue by lfarkas** [GoogleContainerTools/jib-extensions#72]
it seems there is only a native image maven extension but no gradle. as eg jib itself use gradle it'd be nice to add gradle extension too.
https://plugins.gradle.org/plugin/org.graalvm.plugin.native-image
or:
https://github.com/palantir/gradle-graal

**Comment by chanseokoh** [comment]
I'm sure you already know this, but the Jib Maven extension depends on the official Quarkus Maven plugin. We are aware that there is also the Gradle plugin, but it has been in the preview state forever. We thought we should wait before committing to release a first-party extension until they become stable and there is a userbase big enough to justify spending our resources on it. Right now, I think it isn't really risky to support the alpha plugin, but still, this would be a very low priority for us. Please thumps-up the issue if you want this to happen more quickly. We also welcome contributions.

**Comment by nickcaballero** [comment]
The work to move the Gradle plugin out of beta is here: https://github.com/quarkusio/quarkus/issues/10189

**Comment by chanseokoh** [comment]
@nickcaballero thanks! I subscribed to the Quarkus issue. Once it goes out of beta, we will reconsider the priority. But as we said, we welcome contributions, as our resources are pretty tight.

**Comment by chanseokoh** [comment]
Ugh, sorry folks. I mistakenly mixed Quarkus into this issue where Quarkus has nothing to do with. What a grand mistake! :tired_face: (We already have [Maven](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-quarkus-extension-maven) and [Gradle](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-quarkus-extension-gradle) extensions for Quarkus apps.) Please forget Quarkus.

The issue—as OP described—is that, while Jib has the [Native Image extension for Maven](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-native-image-extension-maven), we don't have a Gradle counterpart.

That said, the Jib Maven extension depends on the official GraalVM [`org.graalvm.nativeimage:native-image-maven-plugin`](https://search.maven.org/artifact/org.graalvm.nativeimage/native-image-maven-plugin), which I think is [superseded by](https://medium.com/graalvm/gradle-and-maven-plugins-for-native-image-with-initial-junit-testing-support-dde00a8caf0b) the new plugin [`org.graalvm.buildtools:native-maven-plugin`](https://graalvm.github.io/native-build-tools/0.9.7.1/maven-plugin.html). It's likely that the new `native-image-plugin` still works in the same way the original one does, so our Jib extension may continue to work well. But if anyone finds it broken, please file a new issue.

For Gradle, they now have an [official Gradle plugin](https://graalvm.github.io/native-build-tools/0.9.7.1/gradle-plugin.html) that looks reliable, so nothing is blocking us to have a Gradle extension for that. Contributions are highly welcome.

**Comment by M-Whitaker** [comment]
For the help wanted on this are you wanting a pull request with a gradle port of the maven plugin that will be taken on as a first party plugin?

I have a forked version with some simple support that maybe of some help.

**Comment by elefeint** [comment]
@M-Whitaker Yes, the gradle plugin should go in `/jib-extension/first-party`; next to the maven plugin.
Thank you!
