### ISSUE TITLE
Support Quarkus fast jar

### ISSUE THREAD

**Issue by asodja** [GoogleContainerTools/jib-extensions#92]
Quarkus "fast jar" is now default for Quarkus from 1.12.0: https://quarkus.io/blog/quarkus-1-12-0-final-released/#fast-jar-as-default.

Previous packaging is still supported via "legacy-jar" property, but it might be removed in the future.

It would be great if also this extension use fast jar by default.

**Comment by asodja** [comment]
Oh, I see there is already a pull request: https://github.com/GoogleContainerTools/jib-extensions/pull/79.

**Comment by zanmagerl** [comment]
I think we can resolve this issue once a new version of Quarkus Maven plugin gets released @mpeddada1

**Comment by mpeddada1** [comment]
@zanmagerl Appreciate your contribution! [jib-quarkus-extension-maven](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-quarkus-extension-maven) v0.1.1 has been released with Quarkus fast jar support.
